#@ load("@ytt:data", "data")
#@ if data.values.filestore.container.enabled:
---
apiVersion: v1
kind: Service
metadata:
  name: minio 
  namespace: #@ data.values.scaffold.namespace
  labels:
    app: minio
  annotations:
    kapp.k14s.io/change-group: "apps.johnfcarter.tech/file-store"
spec:
  selector:
    app: minio
  ports:
    - name: api 
      port: #@ data.values.filestore.connection.port
      targetPort: #@ data.values.filestore.connection.port
      protocol: TCP
    - name: ui
      port: #@ data.values.filestore.container.ui_port
      targetPort: #@ data.values.filestore.container.ui_port
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: #@ data.values.scaffold.namespace
  labels:
    app: minio
  annotations:
    kapp.k14s.io/change-group: "apps.johnfcarter.tech/file-store"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      #@ if data.values.k8s.image_pull_secret.enabled:
      imagePullSecrets:
      -  name: scaffold-regcred
      #@ end
      containers:
      - name: minio
        image: #@ data.values.filestore.container.image
        env:
        - name: BITNAMI_DEBUG
          value: #@ "{}".format(data.values.filestore.container.debug)
        - name: MINIO_REGION
          value: #@ data.values.filestore.connection.region
        - name: MINIO_CONSOLE_PORT_NUMBER
          value: #@ "{}".format(data.values.filestore.container.ui_port)
        - name: MINIO_SERVER_PORT_NUMBER
          value: #@ "{}".format(data.values.filestore.connection.port)
        - name: MINIO_API_PORT_NUMBER
          value: #@ "{}".format(data.values.filestore.connection.port)
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: scaffold-filestore
              key: access_key
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scaffold-filestore
              key: secret_key
#@ end
