#@ load("@ytt:data", "data")
#@ if data.values.document_store.container.enabled:
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb 
  namespace: #@ data.values.scaffold.namespace
  labels:
    app: mongodb
  annotations:
    kapp.k14s.io/change-group: "apps.johnfcarter.tech/document-store"
spec:
  selector:
    app: mongodb
  ports:
    - name: api 
      port: #@ data.values.document_store.container.port
      targetPort: #@ data.values.document_store.container.port
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: #@ data.values.scaffold.namespace
  labels:
    app: mongodb
  annotations:
    kapp.k14s.io/change-group: "apps.johnfcarter.tech/document-store"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      #@ if data.values.k8s.image_pull_secret.enabled:
      imagePullSecrets:
      -  name: scaffold-regcred
      #@ end
      containers:
      - name: mongodb
        image: #@ data.values.document_store.container.image
        env:
        - name: MONGODB_DATABASE
          value: #@ data.values.document_store.container.database
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scaffold-document-store
              key: admin_password
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: scaffold-document-store
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scaffold-document-store
              key: password
#@ end
