#@ load("@ytt:data", "data")
#@ if data.values.k8s.create_namespace:
---
apiVersion: v1
kind: Namespace
metadata:
  name: scaffold
  labels:
    name: #@ data.values.scaffold.namespace
    namespace: #@ data.values.scaffold.namespace
#@ end
